import '../core/pebble_cipher.dart';

/// Remote credentials + identity for the Orb Tumble Trail gray flow.
///
/// Every secret is stored as an obfuscated byte array (never plaintext),
/// generated by `dart run tool/encode_ott_values.dart`. The gray gate stays
/// disabled (native game only) until [endpoint], [appsFlyerKey] and
/// [firebaseProjectNumber] all decode to non-empty strings.
abstract final class OrbTrailConfig {
  static const String appTitle = 'Orb Tumble Trail';
  static const String bundleId = 'com.orbtumble.trailgame';

  /// iOS App Store numeric id — used for GCD lookup and the `store_id` field.
  static const String iosStoreId = '6792779314';

  static const int pushSnoozeSeconds = 259200; // 3 days
  static const int organicRecheckSeconds = 6;

  // ── Encoded secrets (tool/encode_ott_values.dart) ─────────────────────
  // config endpoint — https://orbtumbletrail.com/config.php
  static const List<int> _endpoint = <int>[
    244, 119, 173, 21, 4, 39, 162, 139, 63, 9, 52, 23, 197, 164, 150, 89, 224,
    104, 77, 58, 60, 221, 188, 95, 157, 220, 94, 161, 91, 36, 196, 207, 99, 70,
    215, 49, 160,
  ];
  // privacy policy — https://orbtumbletrail.com/privacy-policy.html
  static const List<int> _privacy = <int>[
    244, 119, 173, 21, 4, 39, 162, 139, 63, 9, 52, 23, 197, 164, 150, 89, 224,
    104, 77, 58, 60, 221, 188, 95, 157, 220, 94, 174, 94, 31, 212, 199, 95, 145,
    148, 57, 159, 70, 117, 26, 42, 106, 204, 16, 120, 232,
  ];
  // support — https://orbtumbletrail.com/support.html
  static const List<int> _support = <int>[
    244, 119, 173, 21, 4, 39, 162, 139, 63, 9, 52, 23, 197, 164, 150, 89, 224,
    104, 77, 58, 60, 221, 188, 95, 157, 220, 94, 177, 97, 38, 206, 213, 110,
    140, 149, 49, 164, 71, 120,
  ];
  // AppsFlyer GCD base.
  static const List<int> _gcd = <int>[
    244, 119, 173, 21, 4, 39, 162, 139, 55, 250, 54, 22, 180, 162, 98, 78, 235,
    100, 78, 63, 63, 234, 243, 110, 92, 210, 158, 171, 27, 31, 204, 217, 112,
    121, 211, 53, 143, 62, 109, 43, 18, 107, 218, 209, 57, 172, 157,
  ];
  // AppsFlyer Dev Key.
  static const List<int> _appsFlyerKey = <int>[
    253, 84, 172, 28, 230, 85, 195, 204, 50, 11, 74, 243, 186, 152, 152, 93,
    173, 106, 72, 83, 58, 164,
  ];
  // Firebase project number (GCM_SENDER_ID).
  static const List<int> _firebaseProject = <int>[
    191, 51, 112, 214, 198, 33, 172, 143, 8, 199, 6, 216,
  ];

  // User-Agent version fragments — bumped per project.
  static const List<int> _webkit = <int>[194, 51, 110, 211, 194, 27, 164, 145];
  static const List<int> _safari = <int>[189, 59, 103, 219];
  static const List<int> _safariTail = <int>[194, 51, 109, 211, 194];

  // OneLink is OPTIONAL — never part of the gate-enable check.
  static const List<int> _oneLinkHost = <int>[
    251, 117, 155, 25, 6, 90, 213, 200, 53, 11, 68, 4, 185, 163, 98, 92, 233,
    89, 71, 66, 65, 220, 188, 105, 147,
  ];

  static String get endpoint => unmaskPebbles(_endpoint);
  static String get privacyUrl => unmaskPebbles(_privacy);
  static String get supportUrl => unmaskPebbles(_support);
  static String get gcdBase => unmaskPebbles(_gcd);
  static String get webKitVersion => unmaskPebbles(_webkit);
  static String get safariVersion => unmaskPebbles(_safari);
  static String get safariTail => unmaskPebbles(_safariTail);
  static String get appsFlyerKey => unmaskPebbles(_appsFlyerKey);
  static String get firebaseProjectNumber => unmaskPebbles(_firebaseProject);
  static String get oneLinkHost => unmaskPebbles(_oneLinkHost);

  static String get storeToken => 'id$iosStoreId';

  /// Gate needs config endpoint + AF key + Firebase project number only.
  /// ⚠️ Do NOT add optional fields (e.g. OneLink) here — a missing optional
  /// value would silently disable the whole gray flow.
  static bool get grayCredentialsReady =>
      endpoint.isNotEmpty &&
      appsFlyerKey.isNotEmpty &&
      firebaseProjectNumber.isNotEmpty;
}
