import 'package:flutter/widgets.dart';
import '../constants/app_icons.dart';

/// Stable string keys are persisted with each habit so the icon set can grow
/// without breaking saved data.
class HabitIcons {
  const HabitIcons._();

  static const Map<String, IconData> _duotone = <String, IconData>{
    'drop': AppIcons.drop,
    'barbell': AppIcons.barbell,
    'personSimpleRun': AppIcons.run,
    'personSimpleWalk': AppIcons.walk,
    'personSimpleBike': AppIcons.bike,
    'book': AppIcons.book,
    'bookOpen': AppIcons.bookOpen,
    'brain': AppIcons.brain,
    'flower': AppIcons.flower,
    'moon': AppIcons.moon,
    'moonStars': AppIcons.moonStars,
    'sun': AppIcons.sun,
    'sunHorizon': AppIcons.sunHorizon,
    'bed': AppIcons.bed,
    'pill': AppIcons.pill,
    'forkKnife': AppIcons.forkKnife,
    'carrot': AppIcons.carrot,
    'coffee': AppIcons.coffee,
    'wine': AppIcons.wine,
    'cigarette': AppIcons.cigarette,
    'deviceMobileSlash': AppIcons.phoneOff,
    'notePencil': AppIcons.editNote,
    'paintBrush': AppIcons.paintBrush,
    'musicNotes': AppIcons.music,
    'code': AppIcons.code,
    'briefcase': AppIcons.briefcase,
    'graduationCap': AppIcons.graduationCap,
    'translate': AppIcons.translate,
    'wallet': AppIcons.wallet,
    'piggyBank': AppIcons.piggyBank,
    'broom': AppIcons.broom,
    'leaf': AppIcons.leaf,
    'tree': AppIcons.tree,
    'mountains': AppIcons.mountains,
    'heart': AppIcons.heart,
    'heartbeat': AppIcons.heartbeat,
    'handsPraying': AppIcons.meditation,
    'handHeart': AppIcons.handHeart,
    'smiley': AppIcons.smiley,
    'shower': AppIcons.shower,
    'sneaker': AppIcons.sneaker,
    'basketball': AppIcons.basketball,
    'soccerBall': AppIcons.soccer,
    'swimmingPool': AppIcons.swim,
    'sparkle': AppIcons.sparkle,
    'star': AppIcons.star,
    'target': AppIcons.target,
    'atom': AppIcons.atom,
    'yinYang': AppIcons.yinYang,
    'alarm': AppIcons.alarm,
  };

  static const Map<String, IconData> _bold = <String, IconData>{
    'drop': AppIcons.drop,
    'barbell': AppIcons.barbell,
    'personSimpleRun': AppIcons.run,
    'personSimpleWalk': AppIcons.walk,
    'personSimpleBike': AppIcons.bike,
    'book': AppIcons.book,
    'bookOpen': AppIcons.bookOpen,
    'brain': AppIcons.brain,
    'flower': AppIcons.flower,
    'moon': AppIcons.moon,
    'moonStars': AppIcons.moonStars,
    'sun': AppIcons.sun,
    'sunHorizon': AppIcons.sunHorizon,
    'bed': AppIcons.bed,
    'pill': AppIcons.pill,
    'forkKnife': AppIcons.forkKnife,
    'carrot': AppIcons.carrot,
    'coffee': AppIcons.coffee,
    'wine': AppIcons.wine,
    'cigarette': AppIcons.cigarette,
    'deviceMobileSlash': AppIcons.phoneOff,
    'notePencil': AppIcons.editNote,
    'paintBrush': AppIcons.paintBrush,
    'musicNotes': AppIcons.music,
    'code': AppIcons.code,
    'briefcase': AppIcons.briefcase,
    'graduationCap': AppIcons.graduationCap,
    'translate': AppIcons.translate,
    'wallet': AppIcons.wallet,
    'piggyBank': AppIcons.piggyBank,
    'broom': AppIcons.broom,
    'leaf': AppIcons.leaf,
    'tree': AppIcons.tree,
    'mountains': AppIcons.mountains,
    'heart': AppIcons.heart,
    'heartbeat': AppIcons.heartbeat,
    'handsPraying': AppIcons.meditation,
    'handHeart': AppIcons.handHeart,
    'smiley': AppIcons.smiley,
    'shower': AppIcons.shower,
    'sneaker': AppIcons.sneaker,
    'basketball': AppIcons.basketball,
    'soccerBall': AppIcons.soccer,
    'swimmingPool': AppIcons.swim,
    'sparkle': AppIcons.sparkle,
    'star': AppIcons.star,
    'target': AppIcons.target,
    'atom': AppIcons.atom,
    'yinYang': AppIcons.yinYang,
    'alarm': AppIcons.alarm,
    // UI-only keys used by achievements.
    'medal': AppIcons.medal,
    'crown': AppIcons.crown,
    'checkCircle': AppIcons.checkCircle,
    'fire': AppIcons.fire,
    'lightning': AppIcons.lightning,
    'rocket': AppIcons.rocket,
    'path': AppIcons.path,
    'planet': AppIcons.planet,
    'gauge': AppIcons.gauge,
    'sphere': AppIcons.sphere,
    'flagBanner': AppIcons.flag,
    'circlesThree': AppIcons.circlesThree,
  };

  static List<String> get keys => _duotone.keys.toList(growable: false);

  static IconData resolve(String key) =>
      _duotone[key] ?? _bold[key] ?? AppIcons.sparkle;

  static IconData resolveBold(String key) =>
      _bold[key] ?? _duotone[key] ?? AppIcons.sparkle;
}
